@base_url=http://localhost:4002
@keycloak_base_url=http://localhost:8080/realms/crash-game/protocol/openid-connect
@access_token={{keycloak_tokens.response.body.access_token}}
# @refresh_token={{login.response.body.refresh_token}}

###

# @name Healthcheck
GET {{base_url}}/health

###

# @name keycloak_tokens
POST {{keycloak_base_url}}/token
Content-Type: application/x-www-form-urlencoded

client_id=crash-game-client
&grant_type=password
&username=player
&password=player123
&scope=openid

###

# @name create_wallet
POST {{base_url}}/wallets
Content-Type: application/json
Authorization: Bearer {{access_token}}

{

}

###

# @name get_player_wallet
GET {{base_url}}/wallets/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
 
 # @name debit_transaction
POST {{base_url}}/debit
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
  "walletId": "8715e3aa-0cf2-4cc6-a315-c6a00e5ea5e2",
  "playerId": "70be2634-f9dc-4592-b258-9ccc482fe7e3",
  "transactionValue": 100
}

###

 # @name credit_transaction
POST {{base_url}}/credit
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
  "walletId": "8715e3aa-0cf2-4cc6-a315-c6a00e5ea5e2",
  "playerId": "70be2634-f9dc-4592-b258-9ccc482fe7e3",
  "transactionValue": 100
}
