name: Setup NodeJs dependencies
description: "Setup Bun and Node.js, then install dependencies with Bun"

runs:
  using: "composite"
  steps:
    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: "package.json"

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
