@base_url=http://localhost:4001



# @name Healthcheck
GET {{base_url}}/health

###

# cole o token da requisição de login do service de wallets em `wallets.http`
# @name bets_history
GET {{base_url}}/games/bets/me?page=1&limit=10
Authorization: Bearer 
Content-Type:  application/json 

### 
 
# cole o token da requisição de login do service de wallets em `wallets.http`
# como não existe a criacao de rounds, criei esse via  SQL puro no DataGrip
 # @name create_bet
POST {{base_url}}/games/bet
Authorization: Bearer 
Content-Type: application/json

{
	"betId": "bet-1",
	"playerId": "70be2634-f9dc-4592-b258-9ccc482fe7e3",
	"amount": 100,
	"betStatus": "WON",
	"roundStatus": "FINALIZED",
	"roundId": "0213d0c9-3a51-49cd-b1a3-97f4770d20e7"
}
