name:
  Push to main CI pipeline

  ### !! FIX  => receber variáveis de ambiente no service do postgres via secrets e criar ambiente isolado para testes

  ### !! FIX  => ao invés de copiar o .env.example com as variáveis exatas do .env, talvez usar secrets ou alguma outra forma de ocultar essas variáveis

on:
  push:
    branches: [main]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    # Sobe o banco de dados no docker
    services:
      postgresql-test:
        image: postgres:18.3-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
          POSTGRES_EXTRA_DATABASES: games,wallets,admin

      kafka:
        image: confluentinc/cp-kafka:7.8.0
        ports:
          - "9092:9092"

    steps:
      # faz o checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # faz o setup do node/bun e instala as dependencias
      - name: "Setup NodeJs deps"
        uses: ./.github/actions/setup-node-deps

      # copia o .env ou .env.example do serviço games
      - name: Copy .env (Games)
        run: cp .env.example .env || cp .env .env
        working-directory: services/games

      # cria o banco wallets_test
      - name: Create wallets_test database
        run: |
          export PGPASSWORD=admin
          until psql -h localhost -U admin -d postgres -c "SELECT 1" > /dev/null 2>&1; do
            echo "Waiting for postgres..."
            sleep 1
          done
          psql -h localhost -U admin -d postgres -c "CREATE DATABASE wallets_test;"
        working-directory: services/wallets

      # gera o cliente do Prisma ORM
      - name: Generate Prisma Client (Games)
        working-directory: services/games
        run: bun db:generate

      # aplica as migrations no banco wallets_test
      - name: Run Prisma Migrate Deploy (Wallets)
        working-directory: services/wallets
        run: |
          NODE_ENV=test \
          DATABASE_URL="postgresql://admin:admin@localhost:5432/wallets_test" \
          PORT=4002 \
          JWT_SECRET="dummy" \
          bun db:migrate:deploy

        # roda testes unitários do serviço games
      - name: Run Game Service Unit Tests
        working-directory: services/games
        run: bun test:cov:unit

        # roda testes e2e do serviço games
      - name: Run Game Service E2E Tests
        working-directory: services/games
        run: bun test:cov:e2e

      # copia o .env ou .env.example do serviço wallets
      - name: Copy .env (Wallets)
        run: cp .env.example .env || cp .env .env
        working-directory: services/wallets

      # gera o cliente do Prisma ORM
      - name: Generate Prisma Client (Wallets)
        working-directory: services/wallets
        run: bun db:generate

        # roda testes unitários do serviço wallets
      - name: Run Wallets Service Unit Tests
        working-directory: services/wallets
        run: bun test:cov:unit

        # roda testes e2e do serviço wallets
      - name: Run Wallets Service E2E Tests
        working-directory: services/wallets
        run: bun test:cov:e2e

      # roda testes unitários do frontend
      - name: Run Frontend Tests
        working-directory: frontend
        run: bun test:cov:unit

        ## TODO => Adicionar playwright para E2E do frontend
