name: Push to main CI pipeline

on:
  push:
    branches: [main]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    # Sobe o banco de dados no docker
    services:
      ### !! FIX => receber variáveis de ambiente via secrets e criar ambiente isolado para testes
      postgresql-test:
        image: postgres:18.3-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
          POSTGRES_EXTRA_DATABASES: games,wallets,admin

    steps:
      # faz o checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # faz o setup do node/bun e instala as dependencias
      - name: "Setup NodeJs deps"
        uses: ./.github/actions/setup-node-deps

      # copia o .env ou .env.example do serviço games
      - name: Copy .env (Games)
        run: cp .env.example .env || cp .env .env
        working-directory: services/games

      # gera o cliente do Prisma ORM
      - name: Generate Prisma Client (Games)
        working-directory: services/games
        run: bun db:generate

        # roda testes unitários do serviço games
      - name: Run Game Service Unit Tests
        working-directory: services/games
        run: bun test:cov:unit

        # roda testes e2e do serviço games
      - name: Run Game Service E2E Tests
        working-directory: services/games
        run: bun test:cov:e2e

      # copia o .env ou .env.example do serviço wallets
      - name: Copy .env (Wallets)
        run: cp .env.example .env || cp .env .env
        working-directory: services/wallets

      # gera o cliente do Prisma ORM
      - name: Generate Prisma Client (Wallets)
        working-directory: services/wallets
        run: bun db:generate

        # roda testes unitários do serviço wallets
      - name: Run Wallets Service Unit Tests
        working-directory: services/wallets
        run: bun test:cov:unit

        # roda testes e2e do serviço wallets
      - name: Run Wallets Service E2E Tests
        working-directory: services/wallets
        run: bun test:cov:e2e

      # roda testes unitários do frontend
      - name: Run Frontend Tests
        working-directory: frontend
        run: bun test:cov:unit

        ## TODO => Adicionar playwright para E2E do frontend
